# Generated by Django 5.2.7 on 2025-11-05 04:44

import cloudinary.models
import cloudinary_storage.storage
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_fr', models.CharField(max_length=255)),
                ('title_en', models.CharField(max_length=255)),
                ('title_ar', models.CharField(max_length=255)),
                ('comment_fr', models.TextField(blank=True)),
                ('comment_en', models.TextField(blank=True)),
                ('comment_ar', models.TextField(blank=True)),
                ('cover_photo', models.ImageField(blank=True, null=True, upload_to='activity_covers/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_fr', models.CharField(max_length=200)),
                ('title_en', models.CharField(max_length=200)),
                ('description_fr', models.TextField()),
                ('description_en', models.TextField()),
                ('image', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(choices=[('benevole', 'Bénévole'), ('entraineur', 'Entraîneur'), ('joueur', 'Joueur'), ('supporter', 'Supporter'), ('autres', 'Autres')], max_length=20)),
                ('message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_replied', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('category', models.CharField(choices=[('commentaire', 'Commentaires et suggestions'), ('question', 'Questions générales'), ('support', 'Support technique'), ('partenariat', 'Partenariat')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('date_envoye', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('couverture', models.ImageField(upload_to='couvertures/')),
                ('fichier', models.FileField(upload_to='documents/')),
            ],
        ),
        migrations.CreateModel(
            name='EquipeMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nom')),
                ('role', models.CharField(choices=[('player', 'Joueur'), ('coach', 'Entraîneur'), ('assistant', 'Assistant'), ('staff', 'Staff technique'), ('manager', 'Manager')], default='player', max_length=20, verbose_name='Rôle')),
                ('position', models.CharField(blank=True, max_length=100, null=True, verbose_name='Poste (ex: Meneur, Pivot)')),
                ('height', models.CharField(blank=True, max_length=20, null=True, verbose_name='Taille (ex: 2m03)')),
                ('weight', models.CharField(blank=True, max_length=20, null=True, verbose_name='Poids (ex: 98 kg)')),
                ('nationality', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nationalité')),
                ('number', models.PositiveIntegerField(blank=True, null=True, verbose_name='Numéro sur le maillot')),
                ('bio_fr', models.TextField(blank=True, null=True, verbose_name='Biographie (FR)')),
                ('bio_en', models.TextField(blank=True, null=True, verbose_name='Biography (EN)')),
                ('photo', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Photo')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "Membre de l'équipe",
                'verbose_name_plural': 'Équipe',
                'ordering': ['role', 'last_name'],
            },
        ),
        migrations.CreateModel(
            name='Fondation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='fondations')),
            ],
        ),
        migrations.CreateModel(
            name='FondationTamkine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_fr', models.CharField(max_length=100)),
                ('title_en', models.CharField(max_length=100)),
                ('title_ar', models.CharField(max_length=100)),
                ('description_fr', models.TextField()),
                ('description_en', models.TextField()),
                ('description_ar', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='fondation_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_fr', models.CharField(max_length=255, verbose_name='Titre (FR)')),
                ('title_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Titre (EN)')),
                ('description_fr', models.TextField(verbose_name='Description (FR)')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Description (EN)')),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "Page d'accueil",
                'verbose_name_plural': "Pages d'accueil",
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_team_name_fr', models.CharField(max_length=255)),
                ('home_team_name_en', models.CharField(max_length=255)),
                ('home_team_name_ar', models.CharField(max_length=255)),
                ('home_team_logo', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='home_team_logo')),
                ('away_team_name_fr', models.CharField(max_length=255)),
                ('away_team_name_en', models.CharField(max_length=255)),
                ('away_team_name_ar', models.CharField(max_length=255)),
                ('away_team_logo', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='away_team_logo')),
                ('location_fr', models.CharField(max_length=255)),
                ('location_en', models.CharField(max_length=255)),
                ('location_ar', models.CharField(max_length=255)),
                ('match_date', models.DateField()),
                ('match_time', models.TimeField()),
                ('description_fr', models.TextField(blank=True, null=True)),
                ('description_en', models.TextField(blank=True, null=True)),
                ('description_ar', models.TextField(blank=True, null=True)),
                ('home_score', models.PositiveIntegerField(default=0)),
                ('away_score', models.PositiveIntegerField(default=0)),
                ('banner_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='match_banner')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-match_date', '-match_time'],
            },
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_fr', models.CharField(max_length=255)),
                ('title_en', models.CharField(max_length=255)),
                ('title_ar', models.CharField(max_length=255)),
                ('content_fr', models.TextField()),
                ('content_en', models.TextField()),
                ('content_ar', models.TextField()),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Image de la mission')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Mission',
                'verbose_name_plural': 'Missions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MotPresident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_fr', models.CharField(max_length=255)),
                ('title_en', models.CharField(blank=True, max_length=255, null=True)),
                ('title_ar', models.CharField(blank=True, max_length=255, null=True)),
                ('description_fr', models.TextField()),
                ('description_en', models.TextField(blank=True, null=True)),
                ('description_ar', models.TextField(blank=True, null=True)),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Image du Président')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Mot du Président',
                'verbose_name_plural': 'Mots du Président',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_fr', models.CharField(max_length=255, verbose_name='Titre (FR)')),
                ('title_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Title (EN)')),
                ('title_ar', models.CharField(blank=True, max_length=255, null=True, verbose_name='العنوان (AR)')),
                ('content_fr', models.TextField(blank=True, null=True, verbose_name='Contenu (FR)')),
                ('content_en', models.TextField(blank=True, null=True, verbose_name='Content (EN)')),
                ('content_ar', models.TextField(blank=True, null=True, verbose_name='المحتوى (AR)')),
                ('image', models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='news/images/', verbose_name='Image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'News',
                'verbose_name_plural': 'News',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('is_replied', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_fr', models.CharField(max_length=255, verbose_name='Nom (FR)')),
                ('name_en', models.CharField(max_length=255, verbose_name='Name (EN)')),
                ('cover_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Cover Image')),
                ('website_url', models.URLField(blank=True, help_text="Partner's official website link", null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Partner',
                'verbose_name_plural': 'Partners',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlatformLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_fr', models.CharField(max_length=100)),
                ('title_en', models.CharField(max_length=100)),
                ('title_ar', models.CharField(max_length=100)),
                ('description_fr', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
                ('description_ar', models.TextField(blank=True)),
                ('url', models.URLField()),
                ('icon', models.ImageField(blank=True, null=True, upload_to='platform_icons/')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_fr', models.CharField(max_length=255)),
                ('title_en', models.CharField(max_length=255)),
                ('title_ar', models.CharField(max_length=255)),
                ('description_fr', models.TextField()),
                ('description_en', models.TextField()),
                ('description_ar', models.TextField()),
                ('photo_couverture', models.ImageField(upload_to='programmes/')),
            ],
        ),
        migrations.CreateModel(
            name='TeamMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_fr', models.CharField(max_length=255)),
                ('title_en', models.CharField(max_length=255)),
                ('title_ar', models.CharField(max_length=255)),
                ('content_fr', models.TextField()),
                ('content_en', models.TextField()),
                ('content_ar', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Valeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_fr', models.CharField(max_length=255)),
                ('title_en', models.CharField(blank=True, max_length=255, null=True)),
                ('title_ar', models.CharField(blank=True, max_length=255, null=True)),
                ('description_fr', models.TextField()),
                ('description_en', models.TextField(blank=True, null=True)),
                ('description_ar', models.TextField(blank=True, null=True)),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Nos Valeurs')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_fr', models.CharField(max_length=255, verbose_name='Titre (Français)')),
                ('title_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Title (English)')),
                ('title_ar', models.CharField(blank=True, max_length=255, null=True, verbose_name='العنوان (Arabe)')),
                ('comment_fr', models.TextField(blank=True, null=True, verbose_name='Commentaire (Français)')),
                ('comment_en', models.TextField(blank=True, null=True, verbose_name='Comment (English)')),
                ('comment_ar', models.TextField(blank=True, null=True, verbose_name='تعليق (Arabe)')),
                ('lien_video', models.URLField(max_length=2000, verbose_name='Lien vidéo')),
                ('cover_image', models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='videotheque/covers/', verbose_name='Image de couverture')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videothèque',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_fr', models.CharField(max_length=200)),
                ('title_en', models.CharField(max_length=200)),
                ('comment_fr', models.TextField(blank=True, null=True)),
                ('comment_en', models.TextField(blank=True, null=True)),
                ('image', models.URLField(blank=True, null=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='base.album')),
            ],
        ),
    ]
