# Generated by Django 5.2.7 on 2025-10-31 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='album',
            name='description_en',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='album',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='title_en',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='album',
            name='title_fr',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='photo',
            name='comment_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='comment_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='title_en',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='photo',
            name='title_fr',
            field=models.CharField(max_length=200),
        ),
    ]
