# Generated by Django 5.2.7 on 2025-10-26 20:13

import cloudinary.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partenaire',
            options={'ordering': ['-created_at'], 'verbose_name': 'Partenaire', 'verbose_name_plural': 'Partenaires'},
        ),
        migrations.AddField(
            model_name='partenaire',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='partenaire',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='partenaire',
            name='video',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Vidéo de présentation'),
        ),
        migrations.AlterField(
            model_name='partenaire',
            name='couverture',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Image de couverture'),
        ),
        migrations.AlterField(
            model_name='partenaire',
            name='site_url',
            field=models.URLField(blank=True, help_text='Lien vers le site web du partenaire', null=True),
        ),
    ]
