# Generated by Django 5.2.7 on 2025-10-26 04:32

import cloudinary_storage.storage
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ('-created_at',), 'verbose_name': 'Video', 'verbose_name_plural': 'Videothèque'},
        ),
        migrations.RemoveField(
            model_name='video',
            name='couverture',
        ),
        migrations.RemoveField(
            model_name='video',
            name='lien',
        ),
        migrations.RemoveField(
            model_name='video',
            name='titre',
        ),
        migrations.AddField(
            model_name='video',
            name='comment_ar',
            field=models.TextField(blank=True, null=True, verbose_name='تعليق (Arabe)'),
        ),
        migrations.AddField(
            model_name='video',
            name='comment_en',
            field=models.TextField(blank=True, null=True, verbose_name='Comment (English)'),
        ),
        migrations.AddField(
            model_name='video',
            name='comment_fr',
            field=models.TextField(blank=True, null=True, verbose_name='Commentaire (Français)'),
        ),
        migrations.AddField(
            model_name='video',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='videotheque/covers/', verbose_name='Image de couverture'),
        ),
        migrations.AddField(
            model_name='video',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='lien_video',
            field=models.URLField(default='https://example.com/video.mp4', max_length=2000, verbose_name='Lien vidéo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='title_ar',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='العنوان (Arabe)'),
        ),
        migrations.AddField(
            model_name='video',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Title (English)'),
        ),
        migrations.AddField(
            model_name='video',
            name='title_fr',
            field=models.CharField(default='Titre par défaut', max_length=255, verbose_name='Titre (Français)'),
            preserve_default=False,
        ),
    ]
