# Generated by Django 5.2.7 on 2025-11-12 10:33

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='home',
            options={'ordering': ['-created_at'], 'verbose_name': "Page d'accueil", 'verbose_name_plural': "Pages d'accueil"},
        ),
        migrations.AlterField(
            model_name='home',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Image'),
        ),
    ]
