# Generated by Django 5.2.7 on 2025-10-26 06:27

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_video_options_remove_video_couverture_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_fr', models.CharField(max_length=255, verbose_name='Titre (FR)')),
                ('title_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Title (EN)')),
                ('title_ar', models.CharField(blank=True, max_length=255, null=True, verbose_name='العنوان (AR)')),
                ('content_fr', models.TextField(blank=True, null=True, verbose_name='Contenu (FR)')),
                ('content_en', models.TextField(blank=True, null=True, verbose_name='Content (EN)')),
                ('content_ar', models.TextField(blank=True, null=True, verbose_name='المحتوى (AR)')),
                ('image', models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='news/images/', verbose_name='Image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'News',
                'verbose_name_plural': 'News',
                'ordering': ('-created_at',),
            },
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.DeleteModel(
            name='Todo',
        ),
    ]
