# Generated by Django 5.2.7 on 2025-10-29 10:58

import cloudinary.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_partenaire_options_partenaire_created_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Partenaire',
        ),
        migrations.AlterModelOptions(
            name='partner',
            options={'ordering': ['-created_at'], 'verbose_name': 'Partner', 'verbose_name_plural': 'Partners'},
        ),
        migrations.RemoveField(
            model_name='partner',
            name='accept_terms',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='email',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='organisation',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='role',
        ),
        migrations.AddField(
            model_name='partner',
            name='cover_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Partner Cover Image'),
        ),
        migrations.AddField(
            model_name='partner',
            name='name_en',
            field=models.CharField(default='Default Partner', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partner',
            name='name_fr',
            field=models.CharField(default='Default Partner FR', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partner',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='video_presentation',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Presentation Video'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='partner',
            name='website_url',
            field=models.URLField(blank=True, help_text='Link to the partner’s official website', max_length=500, null=True),
        ),
    ]
