# Generated by Django 5.1.7 on 2025-03-17 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_blog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Todo',
        ),
    ]
