# Generated by Django 5.2.7 on 2025-11-02 16:51

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_album_created_at_remove_photo_created_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommunityContact',
        ),
        migrations.RenameField(
            model_name='motpresident',
            old_name='titre_ar',
            new_name='title_ar',
        ),
        migrations.RenameField(
            model_name='motpresident',
            old_name='titre_en',
            new_name='title_en',
        ),
        migrations.RenameField(
            model_name='motpresident',
            old_name='titre_fr',
            new_name='title_fr',
        ),
        migrations.AlterField(
            model_name='motpresident',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Image du President'),
        ),
    ]
