# Generated by Django 5.2.7 on 2025-10-30 00:14

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_delete_partenaire_alter_partner_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='video_presentation',
        ),
        migrations.AlterField(
            model_name='partner',
            name='cover_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Cover Image'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='name_en',
            field=models.CharField(max_length=255, verbose_name='Name (EN)'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='name_fr',
            field=models.CharField(max_length=255, verbose_name='Nom (FR)'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='website_url',
            field=models.URLField(blank=True, help_text="Partner's official website link", null=True),
        ),
    ]
