# Generated by Django 5.2.7 on 2025-11-02 19:20

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_delete_communitycontact_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='valeur',
            old_name='titre_ar',
            new_name='title_ar',
        ),
        migrations.RenameField(
            model_name='valeur',
            old_name='titre_en',
            new_name='title_en',
        ),
        migrations.RenameField(
            model_name='valeur',
            old_name='titre_fr',
            new_name='title_fr',
        ),
        migrations.AlterField(
            model_name='valeur',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Nos Valeurs'),
        ),
    ]
