# Generated by Django 5.2.7 on 2025-11-02 20:21

import cloudinary.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_mission_options_mission_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipeMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nom')),
                ('role', models.CharField(choices=[('player', 'Joueur'), ('coach', 'Entraîneur'), ('assistant', 'Assistant'), ('staff', 'Staff technique'), ('manager', 'Manager')], default='player', max_length=20, verbose_name='Rôle')),
                ('position', models.CharField(blank=True, max_length=100, null=True, verbose_name='Poste (ex: Meneur, Pivot)')),
                ('height', models.CharField(blank=True, max_length=20, null=True, verbose_name='Taille (ex: 2m03)')),
                ('weight', models.CharField(blank=True, max_length=20, null=True, verbose_name='Poids (ex: 98 kg)')),
                ('nationality', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nationalité')),
                ('number', models.PositiveIntegerField(blank=True, null=True, verbose_name='Numéro sur le maillot')),
                ('bio_fr', models.TextField(blank=True, null=True, verbose_name='Biographie (FR)')),
                ('bio_en', models.TextField(blank=True, null=True, verbose_name='Biography (EN)')),
                ('photo', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Photo')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "Membre de l'équipe",
                'verbose_name_plural': 'Équipe',
                'ordering': ['role', 'last_name'],
            },
        ),
    ]
