# Generated by Django 5.2.7 on 2025-11-02 23:30

import cloudinary.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_equipemember'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='motpresident',
            options={'ordering': ['-created_at'], 'verbose_name': 'Mot du Président', 'verbose_name_plural': 'Mots du Président'},
        ),
        migrations.AddField(
            model_name='motpresident',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='motpresident',
            name='description_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='motpresident',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='motpresident',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Image du Président'),
        ),
        migrations.AlterField(
            model_name='motpresident',
            name='title_ar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='motpresident',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
