# Generated by Django 5.1.7 on 2025-04-07 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_blog_image_alter_todo_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='motpresi',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
