# Generated by Django 5.2.7 on 2025-11-03 00:49

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_motpresident_options_motpresident_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='attachment',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Pièce jointe (facultative)'),
        ),
        migrations.AddField(
            model_name='contact',
            name='category',
            field=models.CharField(choices=[('comment', 'Commentaires et suggestions'), ('question', 'Questions générales'), ('support', 'Support technique'), ('partner', 'Partenariat')], default='question', max_length=50),
        ),
        migrations.AddField(
            model_name='contact',
            name='subject',
            field=models.CharField(default='Contact sans sujet', max_length=255),
            preserve_default=False,
        ),
    ]
