# Generated by Django 5.2.7 on 2025-11-03 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_contact_attachment_contact_category_contact_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('tel', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('conditions', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='contact',
            name='attachment',
        ),
        migrations.AlterField(
            model_name='contact',
            name='category',
            field=models.CharField(choices=[('commentaire', 'Commentaires et suggestions'), ('question', 'Questions générales'), ('support', 'Support technique'), ('partenariat', 'Partenariat')], max_length=50),
        ),
    ]
