# Generated by Django 5.2.7 on 2025-11-03 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_communitycontact_remove_contact_attachment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(choices=[('benevole', 'Bénévole'), ('entraineur', 'Entraîneur'), ('joueur', 'Joueur'), ('supporter', 'Supporter'), ('autres', 'Autres')], max_length=20)),
                ('message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_replied', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='CommunityContact',
        ),
    ]
