# Generated by Django 5.1.7 on 2025-04-20 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_communitycontact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitycontact',
            name='conditions',
            field=models.BooleanField(),
        ),
    ]
