# Generated by Django 5.1.7 on 2025-04-20 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_alter_communitycontact_conditions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(choices=[('enseignant', 'Enseignant'), ('parent', "Parent d'élève"), ('eleve', 'Élève'), ('autre', 'Autre')], max_length=20)),
                ('organization', models.CharField(blank=True, max_length=100)),
                ('website_url', models.URLField(blank=True)),
                ('phone', models.CharField(max_length=15)),
                ('accept_terms', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
