# Generated by Django 5.1.7 on 2025-04-20 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_partner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='organization',
        ),
        migrations.AddField(
            model_name='partner',
            name='organisation',
            field=models.CharField(default='Non spécifié', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='partner',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='partner',
            name='website_url',
            field=models.URLField(),
        ),
    ]
