# Generated by Django 5.1.7 on 2025-04-20 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_subscriber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriber',
            old_name='subscribed_at',
            new_name='created_at',
        ),
    ]
