# Generated by Django 5.1.7 on 2025-04-20 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_rename_subscribed_at_subscriber_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('url', models.URLField()),
                ('icon', models.ImageField(blank=True, null=True, upload_to='platform_icons/')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
