# Generated by Django 5.1.7 on 2025-04-22 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_platformlink'),
    ]

    operations = [
        migrations.CreateModel(
            name='Valeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='valeurs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
