# Generated by Django 5.1.7 on 2025-04-22 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_valeur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='valeur',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='valeur',
            name='titre',
            field=models.CharField(max_length=255),
        ),
    ]
