# Generated by Django 5.1.7 on 2025-04-22 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_program'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fondation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='fondations')),
            ],
        ),
        migrations.AlterField(
            model_name='valeur',
            name='image',
            field=models.ImageField(upload_to='valeurs'),
        ),
    ]
