# Generated by Django 5.1.7 on 2025-04-22 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_fondation_alter_valeur_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='MotPresident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='mot_president')),
            ],
        ),
    ]
