# Generated by Django 5.1.7 on 2025-04-24 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_delete_motpresi'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('lien', models.URLField()),
                ('couverture', models.ImageField(upload_to='videos_couvertures')),
            ],
        ),
    ]
