# Generated by Django 5.1.7 on 2025-04-25 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0031_mediacontent_delete_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('couverture', models.ImageField(upload_to='couvertures/')),
                ('fichier', models.FileField(upload_to='documents/')),
            ],
        ),
    ]
