# Generated by Django 5.1.7 on 2025-04-25 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0032_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partenaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('couverture', models.ImageField(upload_to='partenaires/')),
                ('site_url', models.URLField()),
            ],
        ),
    ]
