# Generated by Django 5.1.7 on 2025-04-25 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0033_partenaire'),
    ]

    operations = [
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('photo_couverture', models.ImageField(upload_to='programmes/')),
            ],
        ),
        migrations.DeleteModel(
            name='Program',
        ),
    ]
