# Generated by Django 5.1.7 on 2025-04-27 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0034_programme_delete_program'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teammessage',
            old_name='content',
            new_name='content_ar',
        ),
        migrations.AddField(
            model_name='teammessage',
            name='content_en',
            field=models.TextField(default='Default English content'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teammessage',
            name='content_fr',
            field=models.TextField(default='Contenu français par défaut'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teammessage',
            name='title_ar',
            field=models.CharField(default='Contenu arabe par défaut', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teammessage',
            name='title_en',
            field=models.CharField(default='Default English Title', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teammessage',
            name='title_fr',
            field=models.CharField(default='Default français Title', max_length=255),
            preserve_default=False,
        ),
    ]
