# Generated by Django 5.1.7 on 2025-05-11 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0036_activity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='cover_image',
        ),
        migrations.AddField(
            model_name='activity',
            name='cover_photo',
            field=models.ImageField(default='activity_covers/default.jpg', upload_to='activity_covers/'),
            preserve_default=False,
        ),
    ]
