# Generated by Django 5.1.7 on 2025-05-13 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0037_remove_activity_cover_image_activity_cover_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mission',
            old_name='content',
            new_name='content_ar',
        ),
        migrations.RemoveField(
            model_name='mission',
            name='title',
        ),
        migrations.AddField(
            model_name='mission',
            name='content_en',
            field=models.TextField(default='Default content'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mission',
            name='content_fr',
            field=models.TextField(default='Contenu par défaut'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mission',
            name='title_ar',
            field=models.CharField(default='Contenu par défaut', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mission',
            name='title_en',
            field=models.CharField(default='Contenu par défaut', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mission',
            name='title_fr',
            field=models.CharField(default='Contenu par défaut', max_length=255),
            preserve_default=False,
        ),
    ]
