# Generated by Django 5.1.7 on 2025-05-13 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0038_rename_content_mission_content_ar_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='valeur',
            old_name='description',
            new_name='description_ar',
        ),
        migrations.RenameField(
            model_name='valeur',
            old_name='titre',
            new_name='titre_ar',
        ),
        migrations.AddField(
            model_name='valeur',
            name='description_en',
            field=models.TextField(default='Default description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='valeur',
            name='description_fr',
            field=models.TextField(default='Default description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='valeur',
            name='titre_en',
            field=models.CharField(default='Default description', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='valeur',
            name='titre_fr',
            field=models.CharField(default='Default description', max_length=255),
            preserve_default=False,
        ),
    ]
