# Generated by Django 5.1.7 on 2025-05-14 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0039_rename_description_valeur_description_ar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valeur',
            name='description_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='valeur',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='valeur',
            name='image',
            field=models.ImageField(upload_to='valeurs/'),
        ),
        migrations.AlterField(
            model_name='valeur',
            name='titre_ar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='valeur',
            name='titre_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
