# Generated by Django 5.1.7 on 2025-05-14 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0040_alter_valeur_description_ar_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fondation',
            old_name='description',
            new_name='description_ar',
        ),
        migrations.RenameField(
            model_name='fondation',
            old_name='titre',
            new_name='titre_ar',
        ),
        migrations.AddField(
            model_name='fondation',
            name='description_en',
            field=models.TextField(default='No description available in English.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fondation',
            name='description_fr',
            field=models.TextField(default='No description available in fran.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fondation',
            name='titre_en',
            field=models.CharField(default='No description available in English.', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fondation',
            name='titre_fr',
            field=models.CharField(default='No description available in English.', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fondation',
            name='image',
            field=models.ImageField(upload_to='fondations/'),
        ),
    ]
