# Generated by Django 5.1.7 on 2025-05-14 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0041_rename_description_fondation_description_ar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fondation',
            name='description_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fondation',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fondation',
            name='titre_ar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fondation',
            name='titre_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
