# Generated by Django 5.1.7 on 2025-05-14 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0042_alter_fondation_description_ar_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fondation',
        ),
    ]
