# Generated by Django 5.1.7 on 2025-05-14 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0043_delete_fondation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fondation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre_fr', models.CharField(max_length=255)),
                ('titre_en', models.CharField(blank=True, max_length=255, null=True)),
                ('titre_ar', models.CharField(blank=True, max_length=255, null=True)),
                ('description_fr', models.TextField()),
                ('description_en', models.TextField(blank=True, null=True)),
                ('description_ar', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='fondations/')),
            ],
        ),
    ]
