# Generated by Django 5.1.7 on 2025-05-14 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0044_fondation'),
    ]

    operations = [
        migrations.CreateModel(
            name='FondationTamkine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_fr', models.CharField(max_length=255)),
                ('title_en', models.CharField(max_length=255)),
                ('title_ar', models.CharField(max_length=255)),
                ('description_fr', models.TextField()),
                ('description_en', models.TextField()),
                ('description_ar', models.TextField()),
                ('image', models.ImageField(upload_to='fondation_images/')),
            ],
        ),
        migrations.DeleteModel(
            name='Fondation',
        ),
    ]
