# Generated by Django 5.1.7 on 2025-05-14 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0045_fondationtamkine_delete_fondation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fondation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='fondations')),
            ],
        ),
        migrations.AlterField(
            model_name='fondationtamkine',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='fondation_images/'),
        ),
        migrations.AlterField(
            model_name='fondationtamkine',
            name='title_ar',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='fondationtamkine',
            name='title_en',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='fondationtamkine',
            name='title_fr',
            field=models.CharField(max_length=100),
        ),
    ]
