# Generated by Django 5.1.7 on 2025-05-15 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0047_rename_description_motpresident_description_ar_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='programme',
            old_name='description',
            new_name='description_ar',
        ),
        migrations.RenameField(
            model_name='programme',
            old_name='title',
            new_name='title_ar',
        ),
        migrations.AddField(
            model_name='programme',
            name='description_en',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='programme',
            name='description_fr',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='programme',
            name='title_en',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='programme',
            name='title_fr',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
