# Generated by Django 5.1.7 on 2025-05-23 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0048_rename_description_programme_description_ar_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Platform',
        ),
        migrations.RenameField(
            model_name='platformlink',
            old_name='description',
            new_name='description_ar',
        ),
        migrations.RenameField(
            model_name='platformlink',
            old_name='name',
            new_name='title_ar',
        ),
        migrations.AddField(
            model_name='platformlink',
            name='description_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='platformlink',
            name='description_fr',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='platformlink',
            name='title_en',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='platformlink',
            name='title_fr',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
