# Generated by Django 5.1.7 on 2025-05-24 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0049_delete_platform_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='title',
            new_name='title_ar',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='comment',
        ),
        migrations.AddField(
            model_name='activity',
            name='comment_ar',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='comment_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='comment_fr',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='title_en',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activity',
            name='title_fr',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activity',
            name='cover_photo',
            field=models.ImageField(blank=True, null=True, upload_to='activity_covers/'),
        ),
    ]
