# Generated by Django 5.1.7 on 2025-05-24 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0050_rename_title_activity_title_ar_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partenaire',
            old_name='description',
            new_name='description_ar',
        ),
        migrations.RenameField(
            model_name='partenaire',
            old_name='titre',
            new_name='titre_ar',
        ),
        migrations.AddField(
            model_name='partenaire',
            name='description_en',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partenaire',
            name='description_fr',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partenaire',
            name='titre_en',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partenaire',
            name='titre_fr',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
