# Generated by Django 5.1.7 on 2025-05-24 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0051_rename_description_partenaire_description_ar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partenaire',
            name='couverture',
            field=models.ImageField(blank=True, null=True, upload_to='partenaires/'),
        ),
    ]
