# Generated by Django 5.1.7 on 2025-05-24 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0052_alter_partenaire_couverture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partenaire',
            name='description_ar',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='partenaire',
            name='description_en',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='partenaire',
            name='description_fr',
            field=models.TextField(blank=True),
        ),
    ]
