# Generated by Django 5.1.7 on 2025-05-24 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0053_alter_partenaire_description_ar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partenaire',
            name='couverture',
            field=models.ImageField(default='', upload_to='partenaires/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='partenaire',
            name='description_ar',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='partenaire',
            name='description_en',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='partenaire',
            name='description_fr',
            field=models.TextField(),
        ),
    ]
