# Generated by Django 5.2.5 on 2025-10-25 15:18

import cloudinary_storage.storage
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0055_rename_content_blog_content_ar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediacontent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mediacontent',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='mediacontent',
            name='image',
            field=models.ImageField(storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='media_content/'),
        ),
        migrations.AlterField(
            model_name='mediacontent',
            name='titre',
            field=models.CharField(max_length=200),
        ),
    ]
